export const EMPLOYEES_SET = 'EMPLOYEES_SET';
export const EMPLOYEES_SET_SUCCESS = 'EMPLOYEES_SET_SUCCESS';
export const EMPLOYEES_SET_FAIL = 'EMPLOYEES_SET_FAIL';
export const FILTER_SET = 'FILTER_SET';
