export const EMPLOYEE_ADD = 'EMPLOYEE_ADD';
export const EMPLOYEE_ADD_SUCCESS = 'EMPLOYEE_ADD_SUCCESS';
export const EMPLOYEE_ADD_FAIL = 'EMPLOYEE_ADD_FAIL';
export const FIELDS_UPDATE = 'FIELDS_UPDATE';
export const SUBMIT_UPDATE = 'SUBMIT_UPDATE';
